
##################  VARIABLES  ##################



##################  CONSTANTS  #####################

IMG_HEIGHT = 256
IMG_WIDTH = 256

POSES_LIST = ['.ipynb_checkpoints',
 'Boat_Pose_or_Paripurna_Navasana_',
 'Bound_Angle_Pose',
 'Bow_Pose_or_Dhanurasana_',
 'Bridge_Pose_or_Setu_Bandha_Sarvangasana_',
 'Camel_Pose_or_Ustrasana_',
 'Cat_Cow_Pose_or_Marjaryasana_',
 'Cat_Pose',
 'Chair_Pose_or_Utkatasana_',
 'Child_Pose',
 'Cobra_Pose_or_Bhujangasana_',
 'Cockerel_Pose',
 'Corpse_Pose_or_Savasana_',
 'Cow_Face_Pose_or_Gomukhasana_',
 'Cow_Pose',
 'Crane_(Crow)_Pose',
 'Downward-Facing_Dog_pose_or_Adho_Mukha_Svanasana_',
 'Eagle_Pose_or_Garudasana_',
 'Eight-Angle_Pose_or_Astavakrasana_',
 'Extended_Puppy_Pose_or_Uttana_Shishosana_',
 'Extended_Revolved_Side_Angle_Pose_or_Utthita_Parsvakonasana_Twist',
 'Extended_Revolved_Side_Angle_Pose_or_Utthita_Parsvakonasana_Untwist',
 'Extended_Revolved_Triangle_Pose_or_Utthita_Trikonasana_',
 'Feathered_Peacock_Pose_or_Pincha_Mayurasana_',
 'Firefly_Pose_or_Tittibhasana_',
 'Fish_Pose_or_Matsyasana_',
 'Four-Limbed_Staff',
 'Frog_Pose_or_Bhekasana',
 'Garland_Pose_or_Malasana_',
 'Gate_Pose_or_Parighasana_',
 'Half_Lord_of_the_Fishes_Pose_or_Ardha_Matsyendrasana_',
 'Half_Moon_Pose_or_Ardha_Chandrasana_',
 'Handstand_pose_or_Adho_Mukha_Vrksasana_',
 'Happy_Baby_Pose_or_Ananda_Balasana_',
 'Head-to-Knee_Forward_Bend_pose_or_Janu_Sirsasana_',
 'Heron_Pose_or_Krounchasana_',
 'Intense_Side_Stretch_Pose_or_Parsvottanasana_',
 'Legs-Up-the-Wall_Pose_or_Viparita_Karani_',
 'Locust_Pose_or_Salabhasana_',
 'Lotus_pose_padmasana',
 'Low_Lunge_pose_or_Anjaneyasana_',
 'Peacock_Pose_or_Mayurasana_',
 'Pigeon_Pose_or_Kapotasana_',
 'Plank_Pose_or_Kumbhakasana_',
 'Plow_Pose_or_Halasana_',
 'Pose_Dedicated_to_the_Sage_Koundinya_or_Eka_Pada_Koundinyanasana_I_and_II',
 'Rajakapotasana',
 'Reclining_Hand-to-Big-Toe_Pose_or_Supta_Padangusthasana_',
 'Reverse_warrior_pose_or_viparita_virabhadrasana',
 'Revolved_Head-to-Knee_Pose_or_Parivrtta_Janu_Sirsasana_',
 'Scale_Pose_or_Tolasana_',
 'Scorpion_pose_or_vrischikasana',
 'Seated_Forward_Bend_pose_or_Paschimottanasana_',
 'Shoulder-Pressing_Pose_or_Bhujapidasana_',
 'Side-Reclining_Leg_Lift_pose_or_Anantasana_',
 'Side_Crane_(Crow)_Pose_or_Parsva_Bakasana_',
 'Side_Plank_Pose_or_Vasisthasana_',
 'Sitting_pose_1_(normal)',
 'Split_pose',
 'Staff_Pose_',
 'Standing_Forward_Bend_pose_or_Uttanasana_',
 'Standing_Split_pose_or_Urdhva_Prasarita_Eka_Padasana_',
 'Standing_big_toe_hold_pose_or_Utthita_Padangusthasana',
 'Supported_Headstand_pose_or_Salamba_Sirsasana_',
 'Supported_Shoulderstand_pose_or_Salamba_Sarvangasana_',
 'Supta_Baddha_Konasana_',
 'Supta_Virasana_Vajrasana',
 'Tortoise_Pose',
 'Tree_Pose_or_Vrksasana_',
 'Two_legged_inverted_staff_pose_or_dwi_pada_viparita_dandasana',
 'Upward_Bow_(Wheel)_Pose_or_Urdhva_Dhanurasana_',
 'Upward_Facing_Two-Foot_Staff_Pose_or_Dwi_Pada_Viparita_Dandasana_',
 'Upward_Plank_Pose_or_Purvottanasana_',
 'Upward_facing_dog_urdhva_mukha_svanasana',
 'Virasana_or_Vajrasana',
 'Warrior_III_Pose_or_Virabhadrasana_III_',
 'Warrior_II_Pose_or_Virabhadrasana_II_',
 'Warrior_I_Pose_or_Virabhadrasana_I_',
 'Wide-Angle_Seated_Forward_Bend_pose_or_Upavistha_Konasana_',
 'Wide-Legged_Forward_Bend_pose_or_Prasarita_Padottanasana_',
 'Wild_Thing_pose_or_Camatkarasana_',
 'Wind_Relieving_pose_or_Pawanmuktasana',
 'Yogic_sleep_pose_or_Yoganidrasana']


################## VALIDATIONS #################
